spring:
  application:
    name: "bus-lines"
  config:
    import: env.properties
server:
  port: 8080
application:
  baseUrl: "https://api.sl.se/api2/LineData.json?key=${API_KEY}"
  stopPointUrl: "${application.baseUrl}&model=stop"
  journeyPatternUrl: "${application.baseUrl}&model=jour&DefaultTransportModeCode=BUS"